### ISSUE TITLE
Node js not connecting to mysql

### ISSUE THREAD

**Issue by Mrbeyond** [frasnym/Docker-NodeJS-MySQL#2]
The sequelize does not seem to connect with the myqsl server on the conatiner.

First the node is built before mysql is completely connected, and a connection to it was not possible, also,
 if I restart the node container maybe to reconnect even the mysql connetion is established, the error shown was:
 
  parent: Error: connect ECONNREFUSED 127.0.0.1:3306
app_1      |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
app_1      |     errno: -111,
app_1      |     code: 'ECONNREFUSED',
app_1      |     syscall: 'connect',
app_1      |     address: '127.0.0.1',
app_1      |     port: 3308,
app_1      |     fatal: true
app_1      |   },
app_1      |   original: Error: connect ECONNREFUSED 127.0.0.1:3306
app_1      |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
app_1      |     errno: -111,
app_1      |     code: 'ECONNREFUSED',
app_1      |     syscall: 'connect',
app_1      |     address: '127.0.0.1',
app_1      |     port: 3308,
app_1      |     fatal: true
app_1      |   }

This has been a major issue that is common with mysql and node.js using docker these days.

**Comment by noor-muradi** [comment]
add MYSQL_HOST=mysqldb in .env file, it is missing

**Comment by avdhendra** [comment]
MYSQL_HOST env variable already present in file still wont able to connect to mysql > node-mysql-app@1.0.0 start /app

docker-nodejs-mysql-app-1      | > node index.js

docker-nodejs-mysql-app-1      | 

docker-nodejs-mysql-app-1      | Worker: process 20 is up on port 3000

docker-nodejs-mysql-app-1      | ConnectionRefusedError [SequelizeConnectionRefusedError]: connect ECONNREFUSED 172.18.0.2:3306

docker-nodejs-mysql-app-1      |     at ConnectionManager.connect (/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:92:17)

docker-nodejs-mysql-app-1      |     at processTicksAndRejections (internal/process/task_queues.js:95:5)

docker-nodejs-mysql-app-1      |     at async ConnectionManager._connect (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)

docker-nodejs-mysql-app-1      |     at async /app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32

docker-nodejs-mysql-app-1      |     at async ConnectionManager.getConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)

docker-nodejs-mysql-app-1      |     at async /app/node_modules/sequelize/lib/sequelize.js:305:26

docker-nodejs-mysql-app-1      |     at async MySQLQueryInterface.tableExists (/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:102:17)

docker-nodejs-mysql-app-1      |     at async Function.sync (/app/node_modules/sequelize/lib/model.js:939:21)

docker-nodejs-mysql-app-1      |     at async Sequelize.sync (/app/node_modules/sequelize/lib/sequelize.js:377:9) {

docker-nodejs-mysql-app-1      |   parent: Error: connect ECONNREFUSED 172.18.0.2:3306

docker-nodejs-mysql-app-1      |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {

docker-nodejs-mysql-app-1      |     errno: -111,

docker-nodejs-mysql-app-1      |     code: 'ECONNREFUSED',

docker-nodejs-mysql-app-1      |     syscall: 'connect',

docker-nodejs-mysql-app-1      |     address: '172.18.0.2',

docker-nodejs-mysql-app-1      |     port: 3306,

docker-nodejs-mysql-app-1      |     fatal: true

docker-nodejs-mysql-app-1      |   },

docker-nodejs-mysql-app-1      |   original: Error: connect ECONNREFUSED 172.18.0.2:3306

docker-nodejs-mysql-app-1      |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {

docker-nodejs-mysql-app-1      |     errno: -111,

docker-nodejs-mysql-app-1      |     code: 'ECONNREFUSED',

docker-nodejs-mysql-app-1      |     syscall: 'connect',

docker-nodejs-mysql-app-1      |     address: '172.18.0.2',

docker-nodejs-mysql-app-1      |     port: 3306,

docker-nodejs-mysql-app-1      |     fatal: true

docker-nodejs-mysql-app-1      |   }

docker-nodejs-mysql-app-1      | }
